# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "next app"
    before: |
      cd app 
      yarn
      gp sync-done packs
    #init: echo 'init script' # runs during prebuild
    command: yarn dev

  - name: "runnin storybook"
    init: gp sync-await packs
    command: yarn storybook  

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    name: "app"
    onOpen: open-preview
  - port: 7001
    name: "storybook"
    onOpen: open-browser
